# Generated by Django 5.0.4 on 2024-04-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
            ],
        ),
    ]
